version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-offboarding1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: offboarding_db
    ports:
      - "5454:5432"
    volumes:
      - postgres-offboarding-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-offboarding11
    restart: always
    ports:
      - "3054:3054"
    depends_on:
      - postgres

  employee-offboardinh:
    build: ./Employee-offboardinh
    container_name: employee-offboardinh11
    restart: always
    ports:
      - "8057:80"
    depends_on:
      - backend

  hr-offboarding:
    build: ./HR-offboarding
    container_name: hr-offboarding2
    restart: always
    ports:
      - "8058:80"
    depends_on:
      - backend

volumes:
  postgres-offboarding-data:

